// AI 聊天分身 - app.js
var coverPlaying=false,userSignature='',audioCtx=null,musicGain=null,musicTimer=null,toastTimer;
var personas=[
  {id:'p1',name:'小仙女✨',sourceSender:'她',styleSummary:'句子偏短，常用「呜呜」「想你」「抱抱」，喜欢用🥺❤️😘',createdAt:'2024-06-04',signature:'你的小可爱已上线~'},
  {id:'p2',name:'甜甜',sourceSender:'甜',styleSummary:'语气活泼，常用「哈哈」「好呀」',createdAt:'2024-06-05',signature:''}
];
var conversations=[
  {id:'c1',personaId:'p1',title:'与 小仙女✨ 的对话',lastMsg:'抱抱~ 下午有空吗 想去看电影',time:'12:38',personaName:'小仙女✨'},
  {id:'c2',personaId:'p2',title:'与 甜甜 的对话',lastMsg:'好的晚安啦💤',time:'昨天',personaName:'甜甜'}
];
var currentChatPersona=null,wizParticipants=[];
var setupSelectedSender=null,setupPersonaName='',setupPersonaSig='',setupStyleSummary=null;
var MELODY=[{note:440,dur:.4},{note:523,dur:.3},{note:587,dur:.5},{note:523,dur:.3},{note:440,dur:.4},{note:349,dur:.3},{note:330,dur:.6},{note:0,dur:.2},{note:330,dur:.3},{note:349,dur:.3},{note:440,dur:.5},{note:330,dur:.3},{note:294,dur:.6},{note:0,dur:.3},{note:440,dur:.3},{note:523,dur:.3},{note:587,dur:.4},{note:659,dur:.5},{note:587,dur:.3},{note:523,dur:.4},{note:440,dur:.3},{note:349,dur:.3},{note:330,dur:.7},{note:0,dur:.4}];
var EMOJIS='[微笑]🙂,[色]😍,[害羞]😊,[大哭]😭,[呲牙]😁,[惊讶]😲,[愉快]🥰,[亲亲]😘,[爱心]❤️,[玫瑰]🌹,[拥抱]🤗,[强]👍,[握手]🤝,[胜利]✌️,[抱拳]🙏,[OK]🙆,[委屈]🥺,[偷笑]🤭,[白眼]🙄,[困]🥱,[奋斗]💪,[疑问]🤔,[鼓掌]👏,[西瓜]🍉,[啤酒]🍺,[蛋糕]🎂,[礼物]🎁,[月亮]🌙,[太阳]☀️,[飞吻]😘'.split(',');

// Q: single-quote in generated HTML

function toast(m){var t=document.getElementById('toast');t.textContent=m;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(function(){t.classList.remove('show');},2000)}

// ===== 封面 =====
function enterApp(){try{if(coverPlaying&&musicGain){musicGain.gain.linearRampToValueAtTime(0,audioCtx.currentTime+.3);coverPlaying=false;clearTimeout(musicTimer)}}catch(e){}var o=document.getElementById('coverOverlay');o.style.opacity='0';o.style.pointerEvents='none';setTimeout(function(){o.style.display='none'},400)}
function toggleCoverMusic(){coverPlaying=!coverPlaying;var b=document.getElementById('coverMusicBtn'),i=document.getElementById('coverMusicIcon'),l=document.getElementById('coverMusicLabel');if(coverPlaying){if(!audioCtx)startMusic();else{coverPlaying=true;playMelodyLoop()}b.classList.add('playing');i.textContent='🎶';l.textContent='正在播放...'}else{clearTimeout(musicTimer);b.classList.remove('playing');i.textContent='🎵';l.textContent='背景音乐'}}
function startMusic(){audioCtx=new(window.AudioContext||window.webkitAudioContext)();musicGain=audioCtx.createGain();musicGain.gain.value=.06;musicGain.connect(audioCtx.destination);playMelodyLoop()}
function playMelodyLoop(){if(!coverPlaying)return;var t=audioCtx.currentTime;MELODY.forEach(function(m){if(m.note>0){var o=audioCtx.createOscillator();o.type='square';o.frequency.value=m.note;var g=audioCtx.createGain();g.gain.setValueAtTime(.06,t);g.gain.exponentialRampToValueAtTime(.001,t+m.dur*.9);o.connect(g);g.connect(musicGain);o.start(t);o.stop(t+m.dur)}t+=m.dur});musicTimer=setTimeout(function(){playMelodyLoop()},0)}
function editMySig(){var s=prompt('输入你的个性签名（将显示在启动封面）',userSignature);if(s!==null){userSignature=s.trim();document.getElementById('coverSigText').textContent=userSignature||'留住那些温柔的对话';document.getElementById('mySigDisplay').innerHTML=(userSignature||'未设置')+'<span class="arr">></span>'}}

// ===== Tab =====
function switchTab(n){document.querySelectorAll('.tab').forEach(function(t){t.classList.remove('active')});document.querySelectorAll('.page').forEach(function(p){p.classList.remove('active')});var t=document.querySelector('[data-page="'+n+'"]');var p=document.getElementById(n+'-page');if(t)t.classList.add('active');if(p)p.classList.add('active');if(n==='list')refreshConvList();if(n==='home')refreshHome();if(n==='settings')refreshSettings()}

// ===== 会话列表 =====
function refreshConvList(){var e=document.getElementById('convList');if(conversations.length===0){e.innerHTML='<div style="text-align:center;padding:80px 30px"><div style="font-size:56px;margin-bottom:16px">💕</div><div style="font-size:18px;font-weight:600;color:#333;margin-bottom:8px">还没有对话</div><div style="font-size:14px;color:#999;line-height:20px;margin-bottom:28px">点击右下角 + 按钮<br>导入和她的聊天记录</div><button class="btn-green" style="width:auto;display:inline-block" onclick="openWizard()">导入聊天记录</button></div>'}else{var h='';conversations.forEach(function(c,i){var bg=c.personaId==='p1'?'background:#FF9EAF':'';h+='<button class="conv-item" onclick="openChat(&quot;'+c.personaId+'&quot;,&quot;'+c.personaName+'&quot;)"><div class="conv-avt" style="'+bg+'">'+c.personaName[0]+'</div><div class="conv-center"><div class="conv-name">'+c.personaName+'</div><div class="conv-preview">'+c.lastMsg+'</div></div><div class="conv-right"><div class="conv-time">'+c.time+'</div></div></button>';if(i<conversations.length-1)h+='<div class="conv-sep"></div>'});e.innerHTML=h}}
function handleFabPress(){if(personas.length===0){openPersonaSetup();return}var o=document.getElementById('sheetOptions');o.innerHTML='<div class="sheet-opt" onclick="doAction(&quot;import&quot;)"><span style="font-size:28px;display:block;margin-bottom:4px">📂</span>导入新的聊天记录</div><div class="sheet-opt" onclick="doAction(&quot;persona&quot;)" style="border-bottom:none"><span style="font-size:28px;display:block;margin-bottom:4px">✨</span>创建新的分身</div>';document.getElementById('actionSheet').classList.add('show')}
function doAction(t){hideSheet();if(t==='import')openWizard();if(t==='persona')openPersonaSetup()}
function hideSheet(){document.getElementById('actionSheet').classList.remove('show')}

// ===== 首页 =====
function refreshHome(){document.getElementById('statMsg').textContent='280 条';document.getElementById('statPersona').textContent=personas.length+' 个';document.getElementById('hintConvs').textContent=conversations.length+' 个对话'}
function refreshSettings(){document.getElementById('settingsPersonaCnt').innerHTML=personas.length+' 个分身<span class="arr">></span>'}

// ===== 聊天 =====
function openChat(pid,pn){currentChatPersona=personas.find(function(p){return p.id===pid});document.getElementById('chatOverlay').classList.add('show');document.getElementById('mainArea').style.display='none';document.querySelector('.tab-bar').style.display='none';document.getElementById('chatNavTitle').textContent=pn;document.getElementById('chatThinkingAvt').textContent=pn[0];var b=document.getElementById('chatBody');b.innerHTML='';b.appendChild(buildTs('12:30'));b.appendChild(buildMsg('her',pn[0],'呜呜 想你了🥺'));b.appendChild(buildMsg('me','','我也想你呀 ❤️'));b.appendChild(buildTs('12:32'));b.appendChild(buildMsg('her',pn[0],'今天吃了吗 我还没起床嘿嘿'));b.appendChild(buildMsg('me','','吃啦 快起来吃点东西'));b.appendChild(buildTs('12:35'));b.appendChild(buildMsg('her',pn[0],'不想起啦 被窝里好暖和😴<br>昨晚梦到你了'));b.appendChild(buildMsg('me','','梦到什么了'));b.appendChild(buildMsg('her',pn[0],'梦到我们去成都吃火锅🍲<br>好开心的'));b.appendChild(buildMsg('me','','哈哈哈 抱抱🫂'));b.appendChild(buildTs('12:38'));b.appendChild(buildMsg('her',pn[0],'抱抱~ 下午有空吗 想去看电影'));b.appendChild(buildMsg('me','','有空的 想看什么'));resetUI();scrollChat()}
function closeChat(){document.getElementById('chatOverlay').classList.remove('show');document.getElementById('mainArea').style.display='flex';document.querySelector('.tab-bar').style.display='flex';refreshConvList()}
function buildTs(t){var d=document.createElement('div');d.className='time-stamp';d.textContent=t;return d}
function buildMsg(side,av,text){var d=document.createElement('div');d.className='msg-row'+(side==='me'?' me':'');if(side==='me'){d.innerHTML='<div class="avt-wrap"><div class="avt me">我</div></div><div class="msg-body"><div class="bubble me">'+text+'</div></div>'}else{d.innerHTML='<div class="avt-wrap"><div class="avt her">'+av+'</div></div><div class="msg-body"><div class="bubble her">'+text+'</div></div>'}return d}
function scrollChat(){setTimeout(function(){var b=document.getElementById('chatBody');if(b)b.scrollTop=b.scrollHeight},50)}
function closeChatPanels(){document.getElementById('chatEmojiPanel').classList.remove('show');document.getElementById('chatFuncPanel').classList.remove('show')}
function toggleChatEmoji(){document.getElementById('chatFuncPanel').classList.remove('show');document.getElementById('chatEmojiPanel').classList.toggle('show')}
function toggleChatFunc(){document.getElementById('chatEmojiPanel').classList.remove('show');document.getElementById('chatFuncPanel').classList.toggle('show')}
function toggleChatVoice(){var inp=document.getElementById('chatInput'),rec=document.getElementById('chatRecordBtn'),btn=document.getElementById('chatVoiceBtn');closeChatPanels();if(inp.style.display===''){inp.style.display='none';rec.classList.add('show');btn.textContent='⌨'}else{inp.style.display='';rec.classList.remove('show');btn.textContent='🎤'}updateChatSendBtn()}
function resetUI(){var inp=document.getElementById('chatInput');inp.style.display='';document.getElementById('chatRecordBtn').classList.remove('show');document.getElementById('chatVoiceBtn').textContent='🎤';document.getElementById('chatThinking').classList.remove('show')}
function startRecord(){document.getElementById('chatRecordBtn').style.background='#E5E5E5'}
function stopRecord(){document.getElementById('chatRecordBtn').style.background='#fff';toast('语音录制功能未完善')}
function updateChatSendBtn(){var inp=document.getElementById('chatInput');if(!inp)return;var has=inp.value.trim().length>0;var isVoice=inp.style.display==='none';var sb=document.getElementById('chatSendBtn'),pb=document.getElementById('chatPlusBtn');if(sb)sb.classList.toggle('show',has&&!isVoice);if(pb)pb.style.display=(has||isVoice)?'none':'flex'}
function chatSend(){var inp=document.getElementById('chatInput');var text=inp.value.trim();if(!text)return;inp.value='';updateChatSendBtn();closeChatPanels();var body=document.getElementById('chatBody'),think=document.getElementById('chatThinking');body.appendChild(buildMsg('me','',text));think.classList.add('show');scrollChat();var replies=['哈哈哈 你真好🥰','嗯嗯 知道啦~','我也觉得诶！','好呀好呀','呜呜 感动到了😭','你也是哦 抱抱🫂','哈哈哈笑死我了😂','嗯嗯 想你啦❤️','哇 真的吗！','太开心了嘿嘿~'];setTimeout(function(){think.classList.remove('show');body.appendChild(buildMsg('her',currentChatPersona?currentChatPersona.name[0]:'她',replies[Math.floor(Math.random()*replies.length)]));scrollChat();think.classList.add('show')},1500+Math.random()*2000)}

// ===== 导入向导 =====
function openWizard(){document.getElementById('wizardOverlay').classList.add('show');renderWizard('select')}
function closeWizard(){document.getElementById('wizardOverlay').classList.remove('show');refreshHome();refreshConvList()}
function renderWizard(step){var s1=document.getElementById('wizSteps'),b=document.getElementById('wizBody');var dots='<div class="wiz-steps-bar">';['选择文件','解析中','完成'].forEach(function(l,i){var c='';if(step==='select'&&i===0)c='on';if(step==='parsing'&&i===0)c='done';if(step==='parsing'&&i===1)c='on';if(step==='result'&&i<=1)c='done';if(step==='result'&&i===2)c='on';dots+='<div class="wiz-step-item"><div class="wiz-step-dot '+c+'">'+(c==='done'?'✓':'')+'</div><div class="wiz-step-label '+(c==='on'?'on':'')+'">'+l+'</div></div>';if(i<2)dots+='<div class="wiz-step-line '+(i<=0&&step!=='select'?'done':'')+'"></div>'});dots+='</div>';s1.innerHTML=dots;if(step==='select'){b.innerHTML='<div class="wiz-file-drop" onclick="simulateParse()"><span class="wiz-file-icon">📂</span><div class="wiz-file-title">选择聊天记录文件</div><div class="wiz-file-hint">支持微信导出的 TXT 和 JSON 格式<br>文件大小不超过 50MB</div></div><div style="font-size:11px;color:#CCC;text-align:center;margin-top:16px">提示：导出时选择你和她的聊天即可</div>'}else if(step==='parsing'){b.innerHTML='<div class="wiz-parsing-wrap"><div class="wiz-spin"></div><div class="wiz-parsing-title">正在解析聊天记录</div><div class="wiz-parsing-file">chat_full.txt</div><div class="wiz-prog-bar"><div class="wiz-prog-fill" id="progFill" style="width:0%"></div></div><div class="wiz-prog-text" id="progText">0 / 280 条</div></div>'}else{renderWizResult(b)}}
function simulateParse(){renderWizard('parsing');var f=document.getElementById('progFill'),t=document.getElementById('progText'),i=0;var timer=setInterval(function(){i+=Math.floor(Math.random()*40)+10;if(i>=280){i=280;clearInterval(timer);finishParse()}if(f)f.style.width=Math.round(i/280*100)+'%';if(t)t.textContent=i+' / 280 条'},180)}
function finishParse(){wizParticipants=[{senderName:'她',persona:personas.find(function(p){return p.sourceSender==='她'})},{senderName:'甜',persona:personas.find(function(p){return p.sourceSender==='甜'})}];renderWizard('result')}
function renderWizResult(el){var h='<div class="wiz-result-wrap"><div class="wiz-check">✓</div><div class="wiz-result-title">解析完成</div>';h+='<div class="wiz-summary"><div class="wiz-summary-row"><span class="wiz-summary-l">消息总数</span><span class="wiz-summary-v">280 条</span></div><div class="wiz-summary-row"><span class="wiz-summary-l">参与者</span><span class="wiz-summary-v">我、她、甜</span></div><div class="wiz-summary-row"><span class="wiz-summary-l">时间跨度</span><span class="wiz-summary-v">2024-01-01 ~ 2024-03-31</span></div><div class="wiz-summary-row"><span class="wiz-summary-l">图片消息</span><span class="wiz-summary-v">12 张</span></div></div>';h+='<div class="wiz-match-card"><div class="wiz-match-title">将这些记录分配给谁？</div><div class="wiz-match-hint">选择已有分身添加数据，或为新联系人创建分身</div>';wizParticipants.forEach(function(m){h+='<div class="wiz-match-item"><div class="wiz-match-info"><div class="wiz-match-avt '+(m.persona?'matched':'unmatched')+'">'+m.senderName[0]+'</div><div><div class="wiz-match-name">《'+m.senderName+'》</div><div class="wiz-match-status '+(m.persona?'matched':'unmatched')+'">'+(m.persona?'已匹配：'+m.persona.name:'未匹配到分身')+'</div></div></div>';h+=m.persona?'<button class="wiz-btn-add" onclick="addToPersona(&quot;'+m.persona.id+'&quot;,&quot;'+m.persona.name+'&quot;)">添加到此分身</button>':'<button class="wiz-btn-new" onclick="createForSender(&quot;'+m.senderName+'&quot;)">创建分身</button>';h+='</div>'});h+='</div>';h+='<button class="wiz-skip-link" onclick="closeWizard()">仅导入数据，暂不分配</button>';h+='<button class="wiz-retry-link" onclick="renderWizard(&quot;select&quot;)">重新导入其他文件</button></div>';el.innerHTML=h}
function addToPersona(pid,pn){toast('✅ 已添加到「'+pn+'」');closeWizard()}
function createForSender(sn){closeWizard();setTimeout(function(){openPersonaSetup(sn)},300)}

// ===== 分身创建 =====
function renderSetupStep(step){var el=document.getElementById("personaSetupContent");var n=setupPersonaName||"",sig=setupPersonaSig||"",av=setupSelectedSender?setupSelectedSender[0]:(n[0]||"她");var h="";h+="<div style=\"padding:20px\">";h+="<div style=\"font-size:22px;font-weight:700;color:#191919;margin-bottom:4px\">设置她的样子</div>";h+="<div style=\"font-size:14px;color:#999;margin-bottom:20px\">设置头像、昵称和签名</div>";h+="<div style=\"text-align:center;margin-bottom:20px\"><div style=\"width:80px;height:80px;border-radius:50%;background:#FF9EAF;display:inline-flex;align-items:center;justify-content:center;font-size:32px;font-weight:600;color:#fff;margin-bottom:8px\">"+av+"</div><div style=\"font-size:13px;color:#999\">点击设置头像</div></div>";h+="<input id=\"snInput\" style=\"display:block;width:100%;padding:14px;background:#fff;border:1px solid #E5E5E5;border-radius:8px;font-size:16px;margin-bottom:10px;outline:none;font-family:inherit\" value=\""+n+"\" placeholder=\"她的昵称\">";h+="<input id=\"ssInput\" style=\"display:block;width:100%;padding:14px;background:#fff;border:1px solid #E5E5E5;border-radius:8px;font-size:16px;margin-bottom:16px;outline:none;font-family:inherit\" value=\""+sig+"\" placeholder=\"她的个性签名\">";h+="<button class=\"btn-green\" onclick=\"doCreatePersona()\">💕 创建</button>";h+="</div>";el.innerHTML=h;}
function openPersonaSetup(pre){setupSelectedSender=pre||null;setupPersonaName=pre||'';setupPersonaSig='';setupStyleSummary=null;document.getElementById('personaSetupOverlay').classList.add('show');renderSetupStep(pre?'select':'config')}
function closePersonaSetup(){document.getElementById('personaSetupOverlay').classList.remove('show');refreshHome();refreshConvList();refreshSettings()}

function selectSender(name){setupSelectedSender=name;setupPersonaName=name;setupStyleSummary=null;renderSetupStep('select')}
function doCreatePersona(){var n=document.getElementById('snInput');setupPersonaName=n?n.value.trim():setupPersonaName;if(!setupPersonaName){toast('请输入她的昵称');return}var sig=document.getElementById('ssInput');setupPersonaSig=sig?sig.value.trim():'';var ss=setupSelectedSender||setupPersonaName;var exist=personas.find(function(p){return p.sourceSender===ss});if(exist){toast('该发送者已有分身：「'+exist.name+'」');return}var np={id:'p'+(personas.length+1)+'_'+Date.now(),name:setupPersonaName,sourceSender:ss,styleSummary:setupStyleSummary||'暂无聊天记录',createdAt:new Date().toISOString().slice(0,10),signature:setupPersonaSig};personas.push(np);conversations.push({id:'c'+(conversations.length+1)+'_'+Date.now(),personaId:np.id,title:'与 '+setupPersonaName+' 的对话',lastMsg:'开始对话吧 💕',time:'刚刚',personaName:setupPersonaName});toast('✅ 分身创建成功！');closePersonaSetup()}

// ===== 分身管理 =====
function openPersonaManage(){document.getElementById('personaOverlay').classList.add('show');renderPersonaList()}
function closePersonaOverlay(){document.getElementById('personaOverlay').classList.remove('show');refreshSettings()}
function renderPersonaList(){var el=document.getElementById('personaContent');if(personas.length===0){el.innerHTML='<div style="text-align:center;padding-top:80px"><div style="font-size:56px;margin-bottom:12px">👤</div><div style="font-size:16px;color:#999;margin-bottom:20px">还没有创建分身</div><button class="btn-green" style="width:auto;display:inline-block" onclick="closePersonaOverlay();openPersonaSetup()">去创建</button></div>';return}var h='';personas.forEach(function(p){h+='<div class="pcard"><div class="pcard-header"><div class="pcard-avt" onclick="toast(&quot;从相册选择头像&quot;)">'+p.name[0]+'</div><div class="pcard-info"><div class="pcard-name">'+p.name+'</div><div class="pcard-src">模仿对象：'+p.sourceSender+'</div><div class="pcard-date">创建于 '+p.createdAt+'</div></div></div>';h+='<button class="pcard-btn-add" onclick="closePersonaOverlay();openWizard()"><span style="font-size:18px;margin-right:8px">📂</span><span style="font-size:14px;font-weight:500;color:#07C160;margin-right:8px">添加聊天记录</span><span style="flex:1;font-size:11px;color:#999;text-align:right">导入更多记录</span></button>';h+='<div class="pcard-actions"><button class="pcard-btn-chat" onclick="closePersonaOverlay();setTimeout(function(){openChat(&quot;'+p.id+'&quot;,&quot;'+p.name+'&quot;)},200)">💬 开始聊天</button><button class="pcard-btn-del" onclick="deletePersona(&quot;'+p.id+'&quot;,&quot;'+p.name+'&quot;)">🗑 删除</button></div></div>'});h+='<button style="display:flex;align-items:center;justify-content:center;width:100%;padding:16px;border-radius:12px;border:1px dashed #E5E5E5;background:#fff;cursor:pointer;font-family:inherit;gap:8px;color:#07C160;font-size:16px;font-weight:500" onclick="closePersonaOverlay();openPersonaSetup()">+ 创建新的分身</button>';el.innerHTML=h}
function deletePersona(id,name){if(!confirm('确认删除「'+name+'」？相关对话也会被删除。'))return;personas=personas.filter(function(p){return p.id!==id});conversations=conversations.filter(function(c){return c.personaId!==id});toast('已删除「'+name+'」');renderPersonaList();refreshConvList();refreshHome();refreshSettings()}

// ===== Emoji 初始化 =====
(function(){var g=document.getElementById('chatEmojiGrid');if(!g)return;EMOJIS.forEach(function(e){var p=e.split(']'),k=p[0]+']',em=p[1],c=document.createElement('div');c.className='emoji-cell';c.textContent=em;c.onclick=function(){var inp=document.getElementById('chatInput');if(inp)inp.value+=k;updateChatSendBtn()};g.appendChild(c)})})();

// ===== 初始化 =====
refreshConvList();refreshHome();refreshSettings();updateChatSendBtn();
